easy_admin:
    site_name: 'Admin'
    design:
        brand_color: '#1ABC9C'
    entities:
        Product:
          class: App\Entity\Product
        Comanda:
          class: App\Entity\Comanda
        Part:
          class: App\Entity\Part
          list:
            fields: ['id','name','price','stock']
        Service:
          class: App\Entity\Service
          list:
            fields: ['id','name','price','length']
        Technician:
          class: App\Entity\Technician
          list:
            fields: ['id','name','birthdate','postal_code']
        Customer:
          class: App\Entity\Customer
